// Define your targets here

export default [
     'https://cleanbtc.ru',
     'https://bonkypay.com',
     'https://changer.club',
    // 'https://www.fontanka.ru',
    // 'https://superchange.net',
    // 'https://mine.exchange',
    // 'https://platov.co',
    // 'https://tass.com',
    // 'https://ww-pay.net',
    // 'https://delets.cash',
    // 'https://betatransfer.org',
    // 'https://ramon.money',
    // 'https://coinpaymaster.com',
    // 'https://bitokk.biz',
    // 'https://www.netex24.net',
    // 'https://cashbank.pro',
    // 'https://flashobmen.com',
    // 'https://abcobmen.com',
    // 'https://ychanger.net',
    // 'https://multichange.net',
    // 'https://24paybank.ne',
    // 'https://ukraina.ru',
    // 'https://royal.cash',
    // 'https://prostocash.com',
    // 'https://baksman.org',
    // 'https://kupibit.me',
    // 'http://www.fsb.ru',
    // 'https://www.bestchange.ru',
    // 'http://www.sberbank.ru',
    // 'https://www.moex.com',
    // 'http://belta.by',
    // 'https://sputnik.by',
    // 'https://www.tvr.by',
    // 'https://www.sb.by',
    // 'https://belmarket.by',
    // 'https://www.belarus.by',
    // 'https://belarus24.by',
    // 'https://ont.by',
    // 'https://www.024.by',
    // 'https://www.belnovosti.by',
    // 'https://mogilevnews.by',
    // 'https://www.mil.by',
    // 'https://yandex.by',
    // 'https://www.slonves.by',
    // 'http://www.ctv.by',
    // 'https://radiobelarus.by',
    // 'https://radiusfm.by',
    // 'https://alfaradio.by/ ',
    // 'https://radiomir.by',
    // 'https://radiostalica.by',
    // 'https://radiobrestfm.by',
    // 'https://www.tvrmogilev.by',
    // 'https://minsknews.by',
    // 'https://zarya.by',
    // 'https://grodnonews.by',
    // 'https://www.gazprom.ru',
    // 'https://lukoil.ru',
    // 'https://magnit.ru',
    // 'https://www.nornickel.com',
    // 'https://www.surgutneftegas.ru',
    // 'https://www.tatneft.ru',
    // 'https://www.evraz.com/ru',
    // 'https://nlmk.com',
    // 'https://www.sibur.ru',
    // 'https://www.severstal.com',
    // 'https://www.metalloinvest.com',
    // 'https://nangs.org',
    // 'https://rmk-group.ru/ru',
    // 'https://www.tmk-group.ru',
    // 'https://ya.ru',
    // 'https://www.polymetalinternational.com/ru',
    // 'https://www.uralkali.com/ru',
    // 'https://www.eurosib.ru',
    // 'https://omk.ru',
    // 'https://www.sberbank.ru',
    // 'https://www.vtb.ru',
    // 'https://www.gazprombank.ru',
    // 'https://www.gosuslugi.ru',
    // 'https://www.mos.ru/uslugi',
    // 'http://kremlin.ru',
    // 'http://government.ru',
    // 'https://mil.ru',
    // 'https://www.nalog.gov.ru',
    // 'https://customs.gov.ru',
    // 'https://pfr.gov.ru',
    // 'https://rkn.gov.ru',
    // 'https://mail.rkn.gov.ru',
    // 'https://cloud.rkn.gov.ru',
    // 'https://mvd.gov.ru',
    // 'https://pwd.wto.economy.gov.ru',
    // 'https://stroi.gov.ru',
    // 'https://proverki.gov.ru',
    // 'https://ria.ru',
    // 'https://gazeta.ru',
    // 'https://kp.ru',
    // 'https://riafan.ru',
    // 'https://pikabu.ru',
    // 'https://kommersant.ru',
    // 'https://mk.ru',
    // 'https://yaplakal.com',
    // 'https://rbc.ru',
    // 'https://bezformata.com',
    // 'https://promsvyaz.by',
    // 'https://sderbank.ru',
    // 'https://sderbank.com',
    // 'https://alfabank.com',
    // 'https://alfabank.ru',
    // 'https://vtb.com',
    // 'https://open.ru',
    // 'https://rshb.ru',
    // 'https://raiffeisen.ru',
    // 'https://rosbank.ru',
    // 'https://rosneft.com',
    // 'https://tgc1.ru',
    // 'https://tplusgroup.ru',
    // 'https://kuzbassenergo.ru',
    // 'https://interrao.ru',
    // 'https://ogk2.ru',
    // 'https://unipro.energy',
    // 'https://enel.ru',
    // 'https://irkutskenergo.ru',
    // 'https://rushydro.ru',
    // 'https://rosenergoatom.ru',
    // 'https://rosseti.ru',
    // 'https://moesk.ru',
    // 'https://lukoil.com',
    // 'https://nornickel.com',
    // 'https://omz.ru',
    // 'https://polyus.com',
    // 'https://nornik.ru',
    // 'https://fsk-ees.ru',
    // 'https://so-ups.ru',
    // 'https://rao-esv.ru',
    // 'https://energybase.ru',
    // 'https://ogk1.com',
    // 'https://peretok.ru',
    // 'https://vestnik-rushydro.ru',
    // 'https://81.177.108.230',
    // 'https://185.140.151.249',
    // 'https://rosprint.net',
    // 'https://gov.ru',
    // 'https://ru.retn.net',
    // 'https://rt.com',
    'https://mail.ru',
    'https://yandex.ru',
    'https://pochta.ru',
    'https://domclick.ru',
    'https://cian.ru',
    'https://irecommend.ru',
    'https://sbis.ru',
    'https://gosuslugi.ru',
    'https://lenta.ru',
    'https://rambler.ru',
    'https://novostinedeli24.com',
    'https://sberbank.ru',
    'https://mos.ru',
    'https://lentainform.com',
    'https://tinkoff.ru',
    'https://microconnect.ru',
    'https://kontur.ru',
    'https://sbrf.ru',
    'https://mosenergosbyt.ru',
    'https://agroserver.ru',
    'https://stroyinf.ru',
    'https://lemzspb.ru',
    'https://vsn.ru',
    'https://rosatom.ru',
    'https://ooo-nemo.ru',
    'https://atomproekt.com',
    'https://nbdoc.ru',
    'https://vbrr.ru',
    'https://mosoblgaz.ru',
    'https://tektorg.ru',
    'https://roseltorg.ru',
    'https://nalog.ru',
    'https://uslugi.mosreg.ru',
    'https://rosminzdrav.ru',
    'https://mosregu.ru',
    'https://topwar.ru',
    'https://vpk-news.ru',
    'https://militaryarms.ru',
    'https://nachfin.info',
    'https://gazprom.com',
    'https://gazpromavia.ru',
    'https://tyumenniigiprogaz.gazprom.com',
    'https://gazprom-spacesystems.ru',
    'https://gazprombank.com',
    'https://gazprom-neft.com',
    'https://promgaz.gazprom.ru',
    'https://gazprom.ru',
    'https://sibur.ru',
    'https://stroytransgaz.com',
    'https://sogaz.ru',
    'https://novatek.ru',
    'https://alfaradio.by',
    'https://newsua.ru',
    'https://spbexchange.com',
    'https://www.rshb.ru',
    'https://mkb.ru',
    'http://www.otkritiefc.ru',
    'https://www.psbank.ru',
    'https://sovcombank.ru',
    'https://www.raiffeisen.ru',
    'https://yoomoney.ru',
    'https://www.netex24.net',
    'https://ddos-guard.net/ru',
    'https://stormwall.pro',
    'https://qrator.net/ru',
    'https://solidwall.ru',
    'https://miit.ru',
    'https://serbank.ru',
    'https://russian.rt.com',
    'https://aif.ru',
    'https://argumenti.ru',
    'https://vm.ru',
    'https://chetv.ru',
    'https://rkn.gov.ru',
    'https://rtvi.com',
    'https://iecp.ru',
    'https://uc-osnovanie.ru',
    'https://nucrf.ru',
    'https://belinfonalog.ru',
    'https://dtln.ru',
    'https://online.gpb.ru',
]
